name: appwrite
version: 5.0.1+legacy
description: Legacy Appwrite SDK for Flutter (Server v0.13 compatible, Dart 3+ ready)
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^3.0.1
  device_info_plus: ">=9.1.2 <11.0.0"
  package_info_plus: ">=1.4.2 <5.0.0"
  http: ^0.13.4           # seguro con Appwrite 5
  path_provider: ^2.0.9
  web_socket_channel: ^2.4.0
  flutter_web_auth_2: ^3.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
